### ISSUE TITLE
Stripe: Declined card errors not caught when updating billing card

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#215]
If a card is declined when updating the billing card, the error doesn't get caught properly.

https://secure.helpscout.net/conversation/110519605/14329/

**Comment by pippinsplugins** [comment]
[11-Aug-2015 00:19:18 UTC] PHP Fatal error: Uncaught exception 'Stripe\Error\Card' with message 'Your card was declined.' in C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiRequestor.php:148

Stack trace:

#0 C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiRequestor.php(256): Stripe\ApiRequestor->handleApiError('{? "error": {?...', 402, Array)

#1 C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiRequestor.php(107): Stripe\ApiRequestor->_interpretResponse('{? "error": {?...', 402)

#2 C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiResource.php(105): Stripe\ApiRequestor->request('post', '/v1/customers/c...', Array, Array)

#3 C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiResource.php(98): Str in C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiRequestor.php on line 148



The full stack trace from the page with WP_DEBUG enabled:





( ! ) Fatal error: Uncaught exception 'Stripe\Error\Card' with message 'Your card was declined.' in C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiRequestor.php on line 148

( ! ) Stripe\Error\Card: Your card was declined. in C:\Users\Administrator\Documents\GitHub\cswealth\wp-content\plugins\restrict-content-pro\includes\libraries\stripe\lib\ApiRequestor.php on line 148

Call Stack

# Time Memory Function Location

1 0.0002 151544 {main}( ) ...\index.php:0

2 0.0003 152640 require( 'C:\Users\Administrator\Documents\GitHub\cswealth\wp-blog-header.php' ) ...\index.php:17

3 0.0004 155784 require_once( 'C:\Users\Administrator\Documents\GitHub\cswealth\wp-load.php' ) ...\wp-blog-header.php:12

4 0.0006 157952 require_once( 'C:\Users\Administrator\Documents\GitHub\cswealth\wp-config.php' ) ...\wp-load.php:37

5 0.0008 175488 require_once( 'C:\Users\Administrator\Documents\GitHub\cswealth\wp-settings.php' ) ...\wp-config.php:81

6 1.0921 5723576 do_action( ) ...\wp-settings.php:353

7 1.1384 6446456 call_user_func_array:{C:\Users\Administrator\Documents\GitHub\cswealth\wp-includes\plugin.php:496} ( ) ...\plugin.php:496

8 1.1384 6446472 rcp_process_update_card_form_post( ) ...\plugin.php:496

9 1.1390 6449112 do_action( ) ...\gateway-functions.php:238

10 1.1390 6450128 call_user_func_array:{C:\Users\Administrator\Documents\GitHub\cswealth\wp-includes\plugin.php:496} ( ) ...\plugin.php:496

11 1.1390 6450144 rcp_stripe_update_billing_card( ) ...\plugin.php:496

12 2.3411 6467912 Stripe\Customer->save( ) ...\functions.php:126

13 2.3411 6467960 Stripe\ApiResource->_save( ) ...\Customer.php:47

14 2.3415 6470936 Stripe\ApiResource->_request( ) ...\ApiResource.php:146

15 2.3415 6471192 Stripe\ApiResource::_staticRequest( ) ...\ApiResource.php:98

16 2.3415 6471352 Stripe\ApiRequestor->request( ) ...\ApiResource.php:105

17 3.6319 6471688 Stripe\ApiRequestor->_interpretResponse( ) ...\ApiRequestor.php:107

18 3.6319 6472432 Stripe\ApiRequestor->handleApiError( ) ...\ApiRequestor.php:256
